### ISSUE TITLE
Only one label in one of cluster set from ArxivClusteringP2P

### ISSUE THREAD

**Issue by Hypothesis-Z** [embeddings-benchmark/mteb#1866]
```python
import mteb
t = mteb.get_task('ArxivClusteringP2P',languages=['eng'])
t.load_data()
print(len(set(t.dataset['test'][29]['labels'])))  # output: 1
```
Does the cluster set make any difference to main scores for different models?

**Comment by Muennighoff** [comment]
Interesting yeah it seems like this specific cluster set won't have any impact on the score cuz it is just the same label?

I think to solve this issue we should run a quick model with and without this cluster set and if it indeed does not change the score at all we remove it and make evaluation a little bit cheaper?

**Comment by Samoed** [comment]
FYI, I've calculated metadata for this task https://github.com/embeddings-benchmark/mteb/blob/0a2df2055c93ca6268cbbb0820cc3dc6e5574457/mteb/descriptive_stats/Clustering/ArxivClusteringP2P.json
It seems that previously I haven't calculated it for superseded tasks

**Comment by KennethEnevoldsen** [comment]
Yeah seems like simply removing it and adding a 1 before averaging at the would speed up the task.

Naturally, we already have the `ArxivClusteringP2P.v2` which is used in the new version of the English Benchmark, which doesn't have this issue (by its construction). So it is a nice, but optional fix. 

`ArxivClusteringP2P.v2` is also notably faster to run.

**Comment by Muennighoff** [comment]
Good point; if it is already fixed in `ArxivClusteringP2P.v2` then maybe we can close this

**Comment by Hypothesis-Z** [comment]
ArxivClusteringP2P.v2 simply downsamples each cluster from ArxivClusteringP2P. It is cheaper, but dose it actually fix this issue?

**Comment by KennethEnevoldsen** [comment]
Hi @Hypothesis-Z, you are completely correct, it isn't solved.

**Comment by KennethEnevoldsen** [comment]
To reproduce the error, it is possible to run the following code:

```py
import mteb

task = mteb.get_task("ArxivClusteringP2P.v2")

task.load_data() # takes a while (> 2 min), would be nice to reduce this time of the downloaded data

ds = task.dataset
for i in range(len(ds["test"])):
    print(f"i={i}:",sorted(set(ds["test"]["labels"][i])))
    # i = 29: ['quant-ph']
```

We could naturally remove it, but that would influence backward compatibility, and while it does increase runtime, it does not change the score as:
```py
model = mteb.get_model("sentence-transformers/static-similarity-mrl-multilingual-v1")

eval = mteb.MTEB(tasks=[task])
result = eval.run(model)
res = result[0]

res.scores["test"][0]["v_measures"][29] # 1.0
```
